// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package clone3

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadClone3_tracepoint returns the embedded CollectionSpec for clone3_tracepoint.
func loadClone3_tracepoint() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Clone3_tracepointBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load clone3_tracepoint: %w", err)
	}

	return spec, err
}

// loadClone3_tracepointObjects loads clone3_tracepoint and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*clone3_tracepointObjects
//	*clone3_tracepointPrograms
//	*clone3_tracepointMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadClone3_tracepointObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadClone3_tracepoint()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// clone3_tracepointSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type clone3_tracepointSpecs struct {
	clone3_tracepointProgramSpecs
	clone3_tracepointMapSpecs
	clone3_tracepointVariableSpecs
}

// clone3_tracepointProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type clone3_tracepointProgramSpecs struct {
	Clone3Entry *ebpf.ProgramSpec `ebpf:"clone3_entry"`
}

// clone3_tracepointMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type clone3_tracepointMapSpecs struct {
	Clone3Counts *ebpf.MapSpec `ebpf:"clone3_counts"`
}

// clone3_tracepointVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type clone3_tracepointVariableSpecs struct {
	TargetPid *ebpf.VariableSpec `ebpf:"target_pid"`
}

// clone3_tracepointObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadClone3_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type clone3_tracepointObjects struct {
	clone3_tracepointPrograms
	clone3_tracepointMaps
	clone3_tracepointVariables
}

func (o *clone3_tracepointObjects) Close() error {
	return _Clone3_tracepointClose(
		&o.clone3_tracepointPrograms,
		&o.clone3_tracepointMaps,
	)
}

// clone3_tracepointMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadClone3_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type clone3_tracepointMaps struct {
	Clone3Counts *ebpf.Map `ebpf:"clone3_counts"`
}

func (m *clone3_tracepointMaps) Close() error {
	return _Clone3_tracepointClose(
		m.Clone3Counts,
	)
}

// clone3_tracepointVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadClone3_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type clone3_tracepointVariables struct {
	TargetPid *ebpf.Variable `ebpf:"target_pid"`
}

// clone3_tracepointPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadClone3_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type clone3_tracepointPrograms struct {
	Clone3Entry *ebpf.Program `ebpf:"clone3_entry"`
}

func (p *clone3_tracepointPrograms) Close() error {
	return _Clone3_tracepointClose(
		p.Clone3Entry,
	)
}

func _Clone3_tracepointClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed clone3_tracepoint_bpfel.o
var _Clone3_tracepointBytes []byte
