// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package futex

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type futex_tracepointFutexStartT struct {
	_   structs.HostLayout
	Ts  uint64
	Cmd int32
	_   [4]byte
}

// loadFutex_tracepoint returns the embedded CollectionSpec for futex_tracepoint.
func loadFutex_tracepoint() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Futex_tracepointBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load futex_tracepoint: %w", err)
	}

	return spec, err
}

// loadFutex_tracepointObjects loads futex_tracepoint and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*futex_tracepointObjects
//	*futex_tracepointPrograms
//	*futex_tracepointMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFutex_tracepointObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFutex_tracepoint()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// futex_tracepointSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type futex_tracepointSpecs struct {
	futex_tracepointProgramSpecs
	futex_tracepointMapSpecs
	futex_tracepointVariableSpecs
}

// futex_tracepointProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type futex_tracepointProgramSpecs struct {
	FutexEntry *ebpf.ProgramSpec `ebpf:"futex_entry"`
	FutexExit  *ebpf.ProgramSpec `ebpf:"futex_exit"`
}

// futex_tracepointMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type futex_tracepointMapSpecs struct {
	FutexWaitUs *ebpf.MapSpec `ebpf:"futex_wait_us"`
	StartTimes  *ebpf.MapSpec `ebpf:"start_times"`
}

// futex_tracepointVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type futex_tracepointVariableSpecs struct {
	TargetPid *ebpf.VariableSpec `ebpf:"target_pid"`
}

// futex_tracepointObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFutex_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type futex_tracepointObjects struct {
	futex_tracepointPrograms
	futex_tracepointMaps
	futex_tracepointVariables
}

func (o *futex_tracepointObjects) Close() error {
	return _Futex_tracepointClose(
		&o.futex_tracepointPrograms,
		&o.futex_tracepointMaps,
	)
}

// futex_tracepointMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFutex_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type futex_tracepointMaps struct {
	FutexWaitUs *ebpf.Map `ebpf:"futex_wait_us"`
	StartTimes  *ebpf.Map `ebpf:"start_times"`
}

func (m *futex_tracepointMaps) Close() error {
	return _Futex_tracepointClose(
		m.FutexWaitUs,
		m.StartTimes,
	)
}

// futex_tracepointVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFutex_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type futex_tracepointVariables struct {
	TargetPid *ebpf.Variable `ebpf:"target_pid"`
}

// futex_tracepointPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFutex_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type futex_tracepointPrograms struct {
	FutexEntry *ebpf.Program `ebpf:"futex_entry"`
	FutexExit  *ebpf.Program `ebpf:"futex_exit"`
}

func (p *futex_tracepointPrograms) Close() error {
	return _Futex_tracepointClose(
		p.FutexEntry,
		p.FutexExit,
	)
}

func _Futex_tracepointClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed futex_tracepoint_bpfel.o
var _Futex_tracepointBytes []byte
