// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package sched_switch

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadSched_switch_tracepoint returns the embedded CollectionSpec for sched_switch_tracepoint.
func loadSched_switch_tracepoint() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Sched_switch_tracepointBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load sched_switch_tracepoint: %w", err)
	}

	return spec, err
}

// loadSched_switch_tracepointObjects loads sched_switch_tracepoint and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*sched_switch_tracepointObjects
//	*sched_switch_tracepointPrograms
//	*sched_switch_tracepointMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSched_switch_tracepointObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSched_switch_tracepoint()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// sched_switch_tracepointSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sched_switch_tracepointSpecs struct {
	sched_switch_tracepointProgramSpecs
	sched_switch_tracepointMapSpecs
	sched_switch_tracepointVariableSpecs
}

// sched_switch_tracepointProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sched_switch_tracepointProgramSpecs struct {
	SchedSwitchHandler *ebpf.ProgramSpec `ebpf:"sched_switch_handler"`
}

// sched_switch_tracepointMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sched_switch_tracepointMapSpecs struct {
	SchedOffcpuUs *ebpf.MapSpec `ebpf:"sched_offcpu_us"`
	StartTimes    *ebpf.MapSpec `ebpf:"start_times"`
}

// sched_switch_tracepointVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sched_switch_tracepointVariableSpecs struct {
	TargetPid *ebpf.VariableSpec `ebpf:"target_pid"`
}

// sched_switch_tracepointObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSched_switch_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type sched_switch_tracepointObjects struct {
	sched_switch_tracepointPrograms
	sched_switch_tracepointMaps
	sched_switch_tracepointVariables
}

func (o *sched_switch_tracepointObjects) Close() error {
	return _Sched_switch_tracepointClose(
		&o.sched_switch_tracepointPrograms,
		&o.sched_switch_tracepointMaps,
	)
}

// sched_switch_tracepointMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSched_switch_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type sched_switch_tracepointMaps struct {
	SchedOffcpuUs *ebpf.Map `ebpf:"sched_offcpu_us"`
	StartTimes    *ebpf.Map `ebpf:"start_times"`
}

func (m *sched_switch_tracepointMaps) Close() error {
	return _Sched_switch_tracepointClose(
		m.SchedOffcpuUs,
		m.StartTimes,
	)
}

// sched_switch_tracepointVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSched_switch_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type sched_switch_tracepointVariables struct {
	TargetPid *ebpf.Variable `ebpf:"target_pid"`
}

// sched_switch_tracepointPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSched_switch_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type sched_switch_tracepointPrograms struct {
	SchedSwitchHandler *ebpf.Program `ebpf:"sched_switch_handler"`
}

func (p *sched_switch_tracepointPrograms) Close() error {
	return _Sched_switch_tracepointClose(
		p.SchedSwitchHandler,
	)
}

func _Sched_switch_tracepointClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sched_switch_tracepoint_bpfel.o
var _Sched_switch_tracepointBytes []byte
