// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package mmap

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadMmap_tracepoint returns the embedded CollectionSpec for mmap_tracepoint.
func loadMmap_tracepoint() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Mmap_tracepointBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load mmap_tracepoint: %w", err)
	}

	return spec, err
}

// loadMmap_tracepointObjects loads mmap_tracepoint and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*mmap_tracepointObjects
//	*mmap_tracepointPrograms
//	*mmap_tracepointMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMmap_tracepointObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadMmap_tracepoint()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// mmap_tracepointSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mmap_tracepointSpecs struct {
	mmap_tracepointProgramSpecs
	mmap_tracepointMapSpecs
	mmap_tracepointVariableSpecs
}

// mmap_tracepointProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mmap_tracepointProgramSpecs struct {
	MmapEntry *ebpf.ProgramSpec `ebpf:"mmap_entry"`
	MmapExit  *ebpf.ProgramSpec `ebpf:"mmap_exit"`
}

// mmap_tracepointMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mmap_tracepointMapSpecs struct {
	MmapExecUs *ebpf.MapSpec `ebpf:"mmap_exec_us"`
	StartTimes *ebpf.MapSpec `ebpf:"start_times"`
}

// mmap_tracepointVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mmap_tracepointVariableSpecs struct {
	TargetPid *ebpf.VariableSpec `ebpf:"target_pid"`
}

// mmap_tracepointObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMmap_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type mmap_tracepointObjects struct {
	mmap_tracepointPrograms
	mmap_tracepointMaps
	mmap_tracepointVariables
}

func (o *mmap_tracepointObjects) Close() error {
	return _Mmap_tracepointClose(
		&o.mmap_tracepointPrograms,
		&o.mmap_tracepointMaps,
	)
}

// mmap_tracepointMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMmap_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type mmap_tracepointMaps struct {
	MmapExecUs *ebpf.Map `ebpf:"mmap_exec_us"`
	StartTimes *ebpf.Map `ebpf:"start_times"`
}

func (m *mmap_tracepointMaps) Close() error {
	return _Mmap_tracepointClose(
		m.MmapExecUs,
		m.StartTimes,
	)
}

// mmap_tracepointVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadMmap_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type mmap_tracepointVariables struct {
	TargetPid *ebpf.Variable `ebpf:"target_pid"`
}

// mmap_tracepointPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMmap_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type mmap_tracepointPrograms struct {
	MmapEntry *ebpf.Program `ebpf:"mmap_entry"`
	MmapExit  *ebpf.Program `ebpf:"mmap_exit"`
}

func (p *mmap_tracepointPrograms) Close() error {
	return _Mmap_tracepointClose(
		p.MmapEntry,
		p.MmapExit,
	)
}

func _Mmap_tracepointClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed mmap_tracepoint_bpfeb.o
var _Mmap_tracepointBytes []byte
