// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package cuda_trace

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadCuda_trace returns the embedded CollectionSpec for cuda_trace.
func loadCuda_trace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Cuda_traceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load cuda_trace: %w", err)
	}

	return spec, err
}

// loadCuda_traceObjects loads cuda_trace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*cuda_traceObjects
//	*cuda_tracePrograms
//	*cuda_traceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCuda_traceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCuda_trace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// cuda_traceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cuda_traceSpecs struct {
	cuda_traceProgramSpecs
	cuda_traceMapSpecs
	cuda_traceVariableSpecs
}

// cuda_traceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cuda_traceProgramSpecs struct {
	UprobeCuMemAlloc    *ebpf.ProgramSpec `ebpf:"uprobe_cuMemAlloc"`
	UretprobeCuMemAlloc *ebpf.ProgramSpec `ebpf:"uretprobe_cuMemAlloc"`
}

// cuda_traceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cuda_traceMapSpecs struct {
	AllocArgs  *ebpf.MapSpec `ebpf:"alloc_args"`
	CudaAllocs *ebpf.MapSpec `ebpf:"cuda_allocs"`
}

// cuda_traceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cuda_traceVariableSpecs struct {
	TargetPid *ebpf.VariableSpec `ebpf:"target_pid"`
}

// cuda_traceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCuda_traceObjects or ebpf.CollectionSpec.LoadAndAssign.
type cuda_traceObjects struct {
	cuda_tracePrograms
	cuda_traceMaps
	cuda_traceVariables
}

func (o *cuda_traceObjects) Close() error {
	return _Cuda_traceClose(
		&o.cuda_tracePrograms,
		&o.cuda_traceMaps,
	)
}

// cuda_traceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCuda_traceObjects or ebpf.CollectionSpec.LoadAndAssign.
type cuda_traceMaps struct {
	AllocArgs  *ebpf.Map `ebpf:"alloc_args"`
	CudaAllocs *ebpf.Map `ebpf:"cuda_allocs"`
}

func (m *cuda_traceMaps) Close() error {
	return _Cuda_traceClose(
		m.AllocArgs,
		m.CudaAllocs,
	)
}

// cuda_traceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCuda_traceObjects or ebpf.CollectionSpec.LoadAndAssign.
type cuda_traceVariables struct {
	TargetPid *ebpf.Variable `ebpf:"target_pid"`
}

// cuda_tracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCuda_traceObjects or ebpf.CollectionSpec.LoadAndAssign.
type cuda_tracePrograms struct {
	UprobeCuMemAlloc    *ebpf.Program `ebpf:"uprobe_cuMemAlloc"`
	UretprobeCuMemAlloc *ebpf.Program `ebpf:"uretprobe_cuMemAlloc"`
}

func (p *cuda_tracePrograms) Close() error {
	return _Cuda_traceClose(
		p.UprobeCuMemAlloc,
		p.UretprobeCuMemAlloc,
	)
}

func _Cuda_traceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cuda_trace_bpfeb.o
var _Cuda_traceBytes []byte
