// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package page_fault

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadPage_fault_tracepoint returns the embedded CollectionSpec for page_fault_tracepoint.
func loadPage_fault_tracepoint() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Page_fault_tracepointBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load page_fault_tracepoint: %w", err)
	}

	return spec, err
}

// loadPage_fault_tracepointObjects loads page_fault_tracepoint and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*page_fault_tracepointObjects
//	*page_fault_tracepointPrograms
//	*page_fault_tracepointMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPage_fault_tracepointObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadPage_fault_tracepoint()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// page_fault_tracepointSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type page_fault_tracepointSpecs struct {
	page_fault_tracepointProgramSpecs
	page_fault_tracepointMapSpecs
	page_fault_tracepointVariableSpecs
}

// page_fault_tracepointProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type page_fault_tracepointProgramSpecs struct {
	PageFaultUserHandler *ebpf.ProgramSpec `ebpf:"page_fault_user_handler"`
}

// page_fault_tracepointMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type page_fault_tracepointMapSpecs struct {
	PageFaultCount *ebpf.MapSpec `ebpf:"page_fault_count"`
}

// page_fault_tracepointVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type page_fault_tracepointVariableSpecs struct {
	TargetPid *ebpf.VariableSpec `ebpf:"target_pid"`
}

// page_fault_tracepointObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPage_fault_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type page_fault_tracepointObjects struct {
	page_fault_tracepointPrograms
	page_fault_tracepointMaps
	page_fault_tracepointVariables
}

func (o *page_fault_tracepointObjects) Close() error {
	return _Page_fault_tracepointClose(
		&o.page_fault_tracepointPrograms,
		&o.page_fault_tracepointMaps,
	)
}

// page_fault_tracepointMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPage_fault_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type page_fault_tracepointMaps struct {
	PageFaultCount *ebpf.Map `ebpf:"page_fault_count"`
}

func (m *page_fault_tracepointMaps) Close() error {
	return _Page_fault_tracepointClose(
		m.PageFaultCount,
	)
}

// page_fault_tracepointVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPage_fault_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type page_fault_tracepointVariables struct {
	TargetPid *ebpf.Variable `ebpf:"target_pid"`
}

// page_fault_tracepointPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPage_fault_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type page_fault_tracepointPrograms struct {
	PageFaultUserHandler *ebpf.Program `ebpf:"page_fault_user_handler"`
}

func (p *page_fault_tracepointPrograms) Close() error {
	return _Page_fault_tracepointClose(
		p.PageFaultUserHandler,
	)
}

func _Page_fault_tracepointClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed page_fault_tracepoint_bpfel.o
var _Page_fault_tracepointBytes []byte
