// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package openat

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadOpenat_tracepoint returns the embedded CollectionSpec for openat_tracepoint.
func loadOpenat_tracepoint() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Openat_tracepointBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load openat_tracepoint: %w", err)
	}

	return spec, err
}

// loadOpenat_tracepointObjects loads openat_tracepoint and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*openat_tracepointObjects
//	*openat_tracepointPrograms
//	*openat_tracepointMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOpenat_tracepointObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadOpenat_tracepoint()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// openat_tracepointSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openat_tracepointSpecs struct {
	openat_tracepointProgramSpecs
	openat_tracepointMapSpecs
	openat_tracepointVariableSpecs
}

// openat_tracepointProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openat_tracepointProgramSpecs struct {
	OpenatEntry *ebpf.ProgramSpec `ebpf:"openat_entry"`
}

// openat_tracepointMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openat_tracepointMapSpecs struct {
	OpenatCounts *ebpf.MapSpec `ebpf:"openat_counts"`
}

// openat_tracepointVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openat_tracepointVariableSpecs struct {
	TargetPid *ebpf.VariableSpec `ebpf:"target_pid"`
}

// openat_tracepointObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOpenat_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type openat_tracepointObjects struct {
	openat_tracepointPrograms
	openat_tracepointMaps
	openat_tracepointVariables
}

func (o *openat_tracepointObjects) Close() error {
	return _Openat_tracepointClose(
		&o.openat_tracepointPrograms,
		&o.openat_tracepointMaps,
	)
}

// openat_tracepointMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOpenat_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type openat_tracepointMaps struct {
	OpenatCounts *ebpf.Map `ebpf:"openat_counts"`
}

func (m *openat_tracepointMaps) Close() error {
	return _Openat_tracepointClose(
		m.OpenatCounts,
	)
}

// openat_tracepointVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadOpenat_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type openat_tracepointVariables struct {
	TargetPid *ebpf.Variable `ebpf:"target_pid"`
}

// openat_tracepointPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOpenat_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type openat_tracepointPrograms struct {
	OpenatEntry *ebpf.Program `ebpf:"openat_entry"`
}

func (p *openat_tracepointPrograms) Close() error {
	return _Openat_tracepointClose(
		p.OpenatEntry,
	)
}

func _Openat_tracepointClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed openat_tracepoint_bpfeb.o
var _Openat_tracepointBytes []byte
