// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package ioctl

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ioctl_tracepointIoctlStartT struct {
	_   structs.HostLayout
	Ts  uint64
	Cmd uint32
	_   [4]byte
}

// loadIoctl_tracepoint returns the embedded CollectionSpec for ioctl_tracepoint.
func loadIoctl_tracepoint() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Ioctl_tracepointBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ioctl_tracepoint: %w", err)
	}

	return spec, err
}

// loadIoctl_tracepointObjects loads ioctl_tracepoint and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ioctl_tracepointObjects
//	*ioctl_tracepointPrograms
//	*ioctl_tracepointMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadIoctl_tracepointObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadIoctl_tracepoint()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ioctl_tracepointSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ioctl_tracepointSpecs struct {
	ioctl_tracepointProgramSpecs
	ioctl_tracepointMapSpecs
	ioctl_tracepointVariableSpecs
}

// ioctl_tracepointProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ioctl_tracepointProgramSpecs struct {
	IoctlEntry *ebpf.ProgramSpec `ebpf:"ioctl_entry"`
	IoctlExit  *ebpf.ProgramSpec `ebpf:"ioctl_exit"`
}

// ioctl_tracepointMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ioctl_tracepointMapSpecs struct {
	IoctlDurationUs *ebpf.MapSpec `ebpf:"ioctl_duration_us"`
	StartTimes      *ebpf.MapSpec `ebpf:"start_times"`
}

// ioctl_tracepointVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ioctl_tracepointVariableSpecs struct {
	TargetPid *ebpf.VariableSpec `ebpf:"target_pid"`
}

// ioctl_tracepointObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadIoctl_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type ioctl_tracepointObjects struct {
	ioctl_tracepointPrograms
	ioctl_tracepointMaps
	ioctl_tracepointVariables
}

func (o *ioctl_tracepointObjects) Close() error {
	return _Ioctl_tracepointClose(
		&o.ioctl_tracepointPrograms,
		&o.ioctl_tracepointMaps,
	)
}

// ioctl_tracepointMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadIoctl_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type ioctl_tracepointMaps struct {
	IoctlDurationUs *ebpf.Map `ebpf:"ioctl_duration_us"`
	StartTimes      *ebpf.Map `ebpf:"start_times"`
}

func (m *ioctl_tracepointMaps) Close() error {
	return _Ioctl_tracepointClose(
		m.IoctlDurationUs,
		m.StartTimes,
	)
}

// ioctl_tracepointVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadIoctl_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type ioctl_tracepointVariables struct {
	TargetPid *ebpf.Variable `ebpf:"target_pid"`
}

// ioctl_tracepointPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadIoctl_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type ioctl_tracepointPrograms struct {
	IoctlEntry *ebpf.Program `ebpf:"ioctl_entry"`
	IoctlExit  *ebpf.Program `ebpf:"ioctl_exit"`
}

func (p *ioctl_tracepointPrograms) Close() error {
	return _Ioctl_tracepointClose(
		p.IoctlEntry,
		p.IoctlExit,
	)
}

func _Ioctl_tracepointClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ioctl_tracepoint_bpfeb.o
var _Ioctl_tracepointBytes []byte
